backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date", name: "dateStart", widget: "datetime" }
      - { label: "End Date", name: "dateEnd", widget: "datetime" }
      - { label: "Media", name: "media", widget: "image" }
      - { label: "Featured Image", name: "featured", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
