backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: unique
    label: "Unique"
    files:
      - label: "Settings"
        name: "global"
        file: "_data/global.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "URL",
              name: "url",
              widget: string
            }
          - {
              label: "Language",
              name: "lang",
              widget: "string",
              default: "en",
              hint: "Use the <a rel=\"noopener noreferrer\" target=\"_blank\" href=\"https://r12a.github.io/app-subtags/\">language tag lookup</a> if you’re not sure which tag to use"
            }
          - {
              label: "Footer",
              name: "footer",
              widget: "text",
              default: "Website by [sb-ph](https://sb-ph.com)",
              hint: Markdown supported
            }
      - label: "Homepage"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "text",
              hint: "Markdown is accepted",
              required: false
            }
          - {
              label: "Projects",
              name: "entries",
              widget: "relation",
              collection: "projects",
              searchFields: "title",
              valueField: "title",
              multiple: true,
              required: false
            }
      - label: "Error page"
        name: "error"
        file: "404.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "text",
              hint: "Markdown is accepted",
              required: false
            }
  - name: posts
    label: "Posts"
    label_singular: "Post"
    folder: "posts"
    preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Body",
          name: "body",
          widget: "text",
          hint: "Markdown is accepted",
          required: false
        }
  - name: pages
    label: "Pages"
    label_singular: "Page"
    folder: "pages"
    preview: false
    create: true
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "text",
          hint: "Markdown is accepted",
          required: false
        }
  - name: projects
    label: "Projects"
    label_singular: "Project"
    folder: "projects"
    preview: false
    create: true
    slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date", name: "dateStart", widget: "datetime", required: false }
      - {
          label: "End Date",
          name: "dateEnd",
          widget: "datetime"
        }
      - {
        label: "Media",
        name: "media",
        widget: "image",
        media_library:
          config:
            max_file_size: 512000
        required: false
        }
      - {
          label: "Featured Image",
          name: "featured",
          widget: "image",
          hint: "If no featured image is selected, it will not be displayed on the homepage",
          required: false
        }
      - {
          label: "Body",
          name: "body",
          widget: "text",
          hint: "Markdown is accepted",
          required: false
        }
